### ISSUE TITLE
can somene explain how to use chatterbot voice

### ISSUE THREAD

**Issue by edwinjose900** [gunthercox/chatterbot-voice#14]
can somene explain how to use chatterbot voice

**Comment by gunthercox** [comment]
Hi @edwinjose900,

Would an example be helpful?

https://github.com/gunthercox/chatterbot-voice/blob/master/examples/example.py

***

The chatterbot-voice module is designed to provide text to speech and speech synthesis capabilities for ChatterBot. It does this by wrapping the `espeak` and `[SpeechRecognition](https://github.com/Uberi/speech_recognition)` libraries.
