### ISSUE TITLE
Error due to Espeak "ModuleNotFoundError: No module named 'espeak'"

### ISSUE THREAD

**Issue by jason0luck** [gunthercox/chatterbot-voice#15]
i tried installing espeak as mentioned
still facing the same issue.
~\Anaconda3\lib\site-packages\chatterbot\chatterbot.py in get_response(self, input_item, conversation_id)
    127     def generate_response(self, input_statement, session_id):
    128         """
--> 129         Return a response based on a given input statement.
    130         """
    131         self.storage.generate_base_query(self, session_id)

~\Anaconda3\lib\site-packages\chatterbot_voice\voice.py in process_response(self, statement, confidence)
     96 
     97     def process_response(self, statement, confidence=None):
---> 98         self.speak(statement.text)
     99         return statement

~\Anaconda3\lib\site-packages\chatterbot_voice\voice.py in speak(self, statement)
     77             return statement.text
     78 
---> 79         from eSpeak import eSpeak
     80         from eSpeak import core as eSpeak_core
     81 

ModuleNotFoundError: No module named 'espeak'

Help me with this.
Many Thanks.

**Comment by gunthercox** [comment]
You're using Windows, correct? If I recall correctly, the espeak library isn't installed on Windows by default.

I've tried to search for a solution but have only come up with [inconclusive answers](https://stackoverflow.com/questions/17547531/how-to-use-espeak-with-python). It seems that installing espeak on windows may entail a number of challenges.

***

I'm open to suggestions if you know of a better library for handline speech synthesis. I've be happy to make or accept changes to switch to it.

**Comment by jason0luck** [comment]
i hope we can resolve this with java script library for speech synthesis  instead of using python packages .

**Comment by mravunni** [comment]
@gunthercox did you get any alternative for espeak

**Comment by gunthercox** [comment]
The [pyttsx3](https://github.com/nateshmbhat/pyttsx3) library by @nateshmbhat seems to be a promising solution for cross platform text to speech.

**Comment by mravunni** [comment]
do we get any working example with pyttsx3 for chatterbot?

**Comment by gunthercox** [comment]
I do not currently have a working example using `pyttsx3`.

**Comment by gunthercox** [comment]
I've switched the project away from using eSpeak in favor of [Festival](https://github.com/festvox/festival). Festival has a number of advantages including the ability to use customized voices.

I'm going to close this ticket off since eSpeak is no longer being used.
