### ISSUE TITLE
No module named speech recognition

### ISSUE THREAD

**Issue by graylu21** [gunthercox/chatterbot-voice#3]
Trying to install chatterbot-voice via 'pip install chatterbot-voice'

and I get this error:
 ImportError: No module named 'speech_recognition'

**Comment by gunthercox** [comment]
I may have an error in the setup script. As a work-around, try running `pip install SpeechRecognition` before you do `pip install chatterbot-voice`.

**Comment by graylu21** [comment]
SpeechRecognition is installing now. Will post if it works, forgot to read the Requirement docs.

**Comment by graylu21** [comment]
It worked! haha next time I'll be sure to read the requirements page. haha Thx

**Comment by gunthercox** [comment]
No problem, I'll correct the issue for the next release. The requirements should have been installed automatically before the rest of the package.
