### ISSUE TITLE
process_response() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by JuneUncle** [gunthercox/chatterbot-voice#4]
Hi, when i run the example, it happened to the following problem
File "C:/Users/IBM_ADMIN/.spyder2-py3/temp.py", line 26, in <module>
    bot_input = bot.get_response(None)
  File "C:\Users\IBM_ADMIN\Anaconda3\lib\site-packages\chatterbot\chatterbot.py", line 223, in get_response
    return self.output.process_response(response, confidence)
TypeError: process_response() takes 2 positional arguments but 3 were given

Can you figure out this problem and how to solve it? Many thanks.

**Comment by gunthercox** [comment]
Hi @JuneUncle, I've pushed up changes that appear to correct this issue. There was a missing parameter on the `process_response` method of the output adapter. Want to test out the code changes to make sure it works for you?

**Comment by gunthercox** [comment]
I've released `chatterbot-voice` version `0.1.1`. The issue should be corrected if you upgrade.
